### ISSUE TITLE
remove hot corners

### ISSUE THREAD

**Issue by JoaquinDecima** [Manjaro-WebDad/jde#104]
Using Hot corners is really annoying, I wish I could remove it.

**Comment by codesardine** [comment]
Set corners to display:none.
then drop the CSS in  /home/username/.config/theme/style.css

**Comment by JoaquinDecima** [comment]
What is the ID or class to select display none?
I looked for it in the css of the theme of the src folder and I did not find anything with the name "corner" or similar

**Comment by codesardine** [comment]
.drag-target, under settings dev tools you have a inspector, turn it on, to inspect HTML/CSS/Javascript
