### ISSUE TITLE
Project fork

### ISSUE THREAD

**Issue by JoaquinDecima** [Manjaro-WebDad/jde#115]
I would like to advise you to start a Fork of the project.
I decided to use MetroUI and am splitting into VUE components. The idea is to move the config away from Main.js and Distribute it in each component. I also want to add a customization interface

At the moment there is not much I did other than rename everything. And it seemed correct to warn me that this existed.

https://gitlab.com/LynxOS/lde

**Comment by codesardine** [comment]
Anyone can fork it, is open source, components is something I already think about, however this project moves very slowly as I have many projects, the current code works but is a bit of a mess and needs structure a build system, sass support etc.
