### ISSUE TITLE
App is minimized when opening

### ISSUE THREAD

**Issue by JoaquinDecima** [Manjaro-WebDad/jde#116]
When opening any App, everything is minimized and shows the desktop

**Comment by codesardine** [comment]
You need to remove starTour() function on main.js as that is specific for my environment.

**Comment by JoaquinDecima** [comment]
It is not the StartTour () because I don't have it. I understand that it is the way to open applications that puts the Desktop in the foreground. Where can I see how the opening of Apps works

**Comment by codesardine** [comment]
I don't have that issue, check utils.py  line 237.

**Comment by JoaquinDecima** [comment]
Tanks i resolved error
