### ISSUE TITLE
How to install it on Ubuntu ?

### ISSUE THREAD

**Issue by yegender124001** [Manjaro-WebDad/jde#117]
I am using ubuntu 20.04. I have downloaded the release and the python requirements. But do not know what to do next.

Thanks

**Comment by yegender124001** [comment]
I found the way

**Comment by essential-existence** [comment]
Hello! Can you describe the step-by-step steps to install this miracle?

**Comment by cydrickn** [comment]
Hi, @yegender124001 can you give some instruction on how you port this to ubuntu
