### ISSUE TITLE
Error in Ubuntu

### ISSUE THREAD

**Issue by yegender124001** [Manjaro-WebDad/jde#118]
I installed Jade-desktop in ubuntu 20.04 and when opened the desktop it give me error:
`Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 11, in <module>
    from lib import menu, icons, utils
  File "/opt/jade/lib/menu.py", line 5, in <module>
    from lib import icons, views
  File "/opt/jade/lib/icons.py", line 5, in <module>
    from j.AK import settings
ModuleNotFoundError: No module named 'j'
`

Please help me.

Thanks

**Comment by codesardine** [comment]
You have the old version, make sure you download the latest targball and all prerequisite dependency's are installed as described in the readme file, you can install Jade-Application-Kit using pip, this is not tested or is supported on ubunto, i have no idea if it works.
