### ISSUE TITLE
Disable manjaro features on other distributions

### ISSUE THREAD

**Issue by JoaquinDecima** [Manjaro-WebDad/jde#99]
I am on Endeavor Linux. Download the code and then compile it.

When starting the application, it starts well but only shows the wallpaper and the shading. The menu or any other option does not appear

![](https://i.postimg.cc/MGMv0q6W/Captura-de-pantalla-de-2020-11-20-15-52-06.png)

The top bar and the bottom dock are from the desktop I'm using until I can compile this one.

**Comment by codesardine** [comment]
You don't need to compile, you need packages that probably don't exist there, https://gitlab.manjaro.org/packages/community/jade/jade-menu-data, you also need to add the missing dock entry's to access apps and settings and most likely replicate some configurations, all the required packages are on gitlab.

**Comment by JoaquinDecima** [comment]
I have working:

- JAK
- Jade-Menu-Data
- Jadesktop

I do not understand if I have to add the dock by hand, and if I have to do it as, or where I should do it.

**Comment by codesardine** [comment]
You only need to add those https://github.com/codesardine/Jadesktop/tree/master/usr/share/applications to your dock, The error above means you don't have branches on endeavour and that is why it fails..

**Comment by codesardine** [comment]
It says on you screenshot line 379 main.js, not sure I understand your question I can see the dock in your screenshot, however the dock is not part of the DE.

**Comment by JoaquinDecima** [comment]
I am referring to the JADE Dock, the bar with the menu and others does not appear.

**Comment by codesardine** [comment]
There is no jade dock, I use a combination of plank and tint2, the applications menu does not appear because the lack of branches breaks it, as a quick fix you can try to delete the function contents on line 379.

**Comment by JoaquinDecima** [comment]
Thank you very much, commenting on this command line:

```JavaScript
desktop.elem(`#${
        LDK.Bridge.getBranch
    }-btn`).checked = true
```

I could already make it work. Proceed to forge it :)
